# Generated by Django 2.0.13 on 2019-03-18 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatetrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cluster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gatetrack.Cluster'),
            preserve_default=False,
        ),
    ]
