# Generated by Django 2.0.13 on 2019-03-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatetrack', '0002_project_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[['Field Development Plan', 'FDP'], ['Execution', 'Execution']], default='Field Development Plan', max_length=100),
        ),
    ]
