# Generated by Django 2.0.13 on 2019-03-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatetrack', '0003_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type_of_scope',
            field=models.CharField(choices=[['Dev/Re-eval/Model', 'Dev/Re-eval/Model'], ['Cased-Hole/P&A/SWAP/BCO', 'Cased-Hole/P&A/SWAP/BCO']], default='Dev/Re-eval/Model', max_length=100),
        ),
    ]
